version: '3.8'
services:
  appointments:
    container_name: appointments
    build: ./appointments
    volumes:
      - ./appointments/code:/usr/src/app
    networks:
      - veterinarian
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  diagnoses:
    container_name: diagnoses
    build: ./diagnoses
    volumes:
      - ./diagnoses/code:/usr/src/app
    networks:
      - veterinarian
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  pets:
    container_name: pets
    build: ./pets
    volumes:
      - ./pets/code:/usr/src/app
    networks:
      - veterinarian
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  veterinarian:
    driver: bridge